name: Build and Package VS Code Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
    
    - name: Compile
      run: npm run compile
    
    - name: Run tests
      run: npm run test
      
    - name: Package extension
      run: npm run package
    
    - name: Upload extension package
      uses: actions/upload-artifact@v3
      with:
        name: launch-sidebar-extension
        path: "*.vsix"
